version: '3'
services:
  back:
    container_name: back
    build: 
      context: ./back/
      dockerfile: docker/cpu.Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - ./back:/workspace
      - ./output:/workspace/output
    entrypoint: python3 api.py
    networks:
      - default

  front:
    container_name: vue
    image: node
    ports:
      - "8080:8080"
    volumes:
      - ./front:/usr/src/app
      - ./output:/usr/src/app/output
    depends_on:
      - back
    working_dir: /usr/src/app
    entrypoint: sh start.sh
    networks:
      - default

networks:
  default:
    driver: bridge